#!/usr/bin/env bash
# Populates .env.test with CSDT Test Account Manager credentials for Playwright CI.
#
# The playwright role is a persistent WordPress user managed in the Test Account
# Manager (wp-admin → Tools → CloudScale Devtools → Login tab → Test Account
# Manager). No temporary account is created by this script.
#
# Usage:
#   bash setup-playwright-test-account.sh
#
# Reads from: ~/Desktop/github/.env.test  (set CSDT_ENV_TEST to override)
# Writes to:  .env.test in this repo (gitignored)
#
# To create the playwright role for the first time:
#   1. Open the Test Account Manager in wp-admin.
#   2. Create a role (e.g. "my_test_account") with role "administrator".
#   3. Copy the .env.test snippet shown in the panel to ~/Desktop/github/.env.test.
#   4. Run this script — it propagates those credentials here.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED_ENV="${CSDT_ENV_TEST:-/Users/cp363412/Desktop/github/.env.test}"

if [[ ! -f "$SHARED_ENV" ]]; then
    echo "ERROR: Shared credentials file not found: $SHARED_ENV"
    echo ""
    echo "Create the playwright role in the Test Account Manager, then copy the"
    echo ".env.test snippet from the panel to: $SHARED_ENV"
    exit 1
fi

for var in CSDT_TEST_SECRET CSDT_TEST_ROLE CSDT_TEST_SESSION_URL CSDT_TEST_LOGOUT_URL; do
    val=$(grep "^${var}=" "$SHARED_ENV" | cut -d'=' -f2- | tr -d '\r')
    [[ -z "$val" ]] && { echo "ERROR: $var not found in $SHARED_ENV"; exit 1; }
    declare "$var=$val"
done

WP_SITE=$(grep '^WP_SITE=' "$SHARED_ENV" | cut -d'=' -f2- | tr -d '\r')
[[ -z "$WP_SITE" ]] && WP_SITE="https://andrewbaker.ninja"

ENV_FILE="${SCRIPT_DIR}/.env.test"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by setup-playwright-test-account.sh — do not commit
# Role: ${CSDT_TEST_ROLE} — persistent user in Test Account Manager (not a temp account)
WP_SITE=${WP_SITE}
WP_BASE_URL=${WP_SITE}
CSDT_TEST_SECRET=${CSDT_TEST_SECRET}
CSDT_TEST_ROLE=${CSDT_TEST_ROLE}
CSDT_TEST_SESSION_URL=${CSDT_TEST_SESSION_URL}
CSDT_TEST_LOGOUT_URL=${CSDT_TEST_LOGOUT_URL}
EOF

echo "Written to .env.test:"
echo "  Role: ${CSDT_TEST_ROLE}"
echo "  Session URL: ${CSDT_TEST_SESSION_URL}"
echo ""
echo "Sessions are created per test run by run-ui-tests.sh and cleaned up automatically."
